export const GET_PAYMENT = "GET_PAYMENT"
export const GET_PAYMENT_RESPONSE = "GET_PAYMENT_RESPONSE"
export const GET_TRANSACTION_HISTORY = "GET_TRANSACTION_HISTORY"
export const GET_TRANSACTION_HISTORY_RESPONSE = "GET_TRANSACTION_HISTORY_RESPONSE"

