export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const GET_USER_DETAILS_RESPONSE = "GET_USER_DETAILS_RESPONSE"
export const UPDATE_USER_PROFILE_DETAILS = "UPDATE_USER_PROFILE_DETAILS"
export const UPDATE_USER_PROFILE_DETAILS_RESPONSE = "UPDATE_USER_PROFILE_DETAILS_RESPONSE"

