export const OTP = "OTP"
export const OTP_RESPONSE = "OTP_RESPONSE"
export const MOBILE_OTP = "MOBILE_OTP"
export const MOBILE_OTP_RESPONSE = "MOBILE_OTP_RESPONSE"
export const REGISTRATION_RESPONSE_CLEAR = "REGISTRATION_RESPONSE_CLEAR";

export const RESEND_OTP = "RESEND_MOBILE_OTP"
export const RESEND_OTP_RESPONSE = "RESEND_MOBILE_OTP_RESPONSE"