export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION"
export const GET_ALL_NOTIFICATION_RESPONSE = "GET_ALL_NOTIFICATION_RESPONSE"
export const GET_ALL_NOTIFICATION_READ = "GET_ALL_NOTIFICATION_READ"
export const GET_ALL_NOTIFICATION_READ_RESPONSE = "GET_ALL_NOTIFICATION_READ_RESPONSE"